import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F7F8FA",
  },
  skipContainer: {
    position: "absolute",
    top: Platform.OS === "android" ? -30 : 10,
    right: 20,
    zIndex: 1,
  },
  skipText: {
    paddingTop: 41,
    paddingRight: 10,
    fontSize: 18,
    color: "#D7D7D7",
  },
  wrapper: {
    marginTop: Platform.OS === "android" ? 10 : 95,
    height: 438,
    paddingTop: Platform.OS === "android" ? 30 : 0,
    paddingBottom: Platform.OS === "android" ? -40 : 0,
  },
  slide: {
    justifyContent: "center",
    alignItems: "center",
  },
  image: {
    width: Platform.OS === "android" ? 330 : 336,
    height: Platform.OS === "android" ? 380 : 438,
    borderRadius: Platform.OS === "android" ? 30 : 13,
  },
  textContainer: {
    alignItems: "center",
    paddingLeft: 39,
    paddingRight: 39,
  },
  titleText: {
    fontFamily: "Poppins",
    fontSize: 33,
    fontWeight: "700",
    lineHeight: 50.85,
    letterSpacing: -0.02,
    textAlign: "center",
  },
  subtitleText: {
    fontFamily: "Poppins",
    fontSize: 16.3,
    fontWeight: "300",
    lineHeight: 15.94,
    textAlign: "center",
    marginTop: 10,
    color: "#8E9295",
  },
  dot: {
    backgroundColor: "rgba(0,0,0,.2)",
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeDot: {
    backgroundColor: "#000",
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  arrowsContainer: {
    backgroundColor: "#FCFCFD",
    width: 154,
    height: 64,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 25,
    paddingLeft: 25,
    paddingBottom: 20,
    paddingTop: 20,
    marginBottom: 32,
  },
  lineSeparator: {
    backgroundColor: "#E6E8EC",
  },
});
